#!/usr/bin/env python

"""usage: relpath FILE1 [FILE2 FILE3 ... DIR]
Print relative path of FILEs with respect to directory DIR.
DIR defaults to "." when not specified or to $HOME without any arguments.
"""

import sys
import os.path

if "-h" in sys.argv or "--help" in sys.argv:
    print __doc__.rstrip()
    sys.exit()

def relativePath(filepath, dirpath):
    pf = filter(None, os.path.abspath(filepath).split(os.sep))
    pd = filter(None, os.path.abspath(dirpath).split(os.sep))
    sepidx = 0
    for sepidx in range(max(len(pf), len(pd)) + 1):
        if sepidx == min(len(pf), len(pd)) or pf[sepidx] != pd[sepidx]:
            break
    updir = '..' + os.sep
    pr = (len(pd) - sepidx) * [updir] + pf[sepidx:]
    if pr:  rv = os.path.join(*pr)
    else:  rv = '.'
    return rv

# get file and reference
fileargs = sys.argv[1:]
if not fileargs:
    fileargs = ["."]
    dirarg = os.path.expanduser("~")
elif len(fileargs) == 1:
    dirarg = "."
else:
    dirarg = fileargs.pop(-1)

for f in fileargs:
    print relativePath(f, dirarg)
